global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "client-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: "resource-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]